#!/usr/bin/env bash
set -euo pipefail

mkdir -p /etc/homeserver

# Setup Groups
wheelarray=($(getent group wheel | cut -d: -f4 |  tr ',' '\n'))

BASE=1000000
STEP=100000
SIZE=65536

mv /etc/subuid /etc/subuid.bak
mv /etc/subgid /etc/subgid.bak 

# Setup home directory for each user in wheel group
i=0
for user in "${wheelarray[@]}"; do
  echo "Setting up home for user: $user"

  start=$((BASE + (i * STEP)))
  echo "$user:$start:$SIZE" | tee -a /etc/subuid /etc/subgid >/dev/null

  if ! grep -q "^$user:" /etc/passwd; then
    echo "[WARNING] Fixed user $user in /etc/passwd"
    getent passwd $user | sudo tee -a /etc/passwd
  fi

  /usr/libexec/setup-home.sh "$user"
  usermod -aG docker $user

  i=$((i + 1))
done
